// worker.throw.outer.js

throw new Error("o_O");

